export { default as ContactsPage } from "./ContactsPage";
export { default as HomePage } from "./HomePage";
export { default as PhotosPage } from "./PhotosPage";
export { default as PostsPage } from "./PostsPage";
export { default as ContactUserPage } from "./ContactUserPage";
export { default as UsersPage } from "./UsersPage";
export { default as AddUserPage } from "./AddUserPage";
export { default as NewsPage } from "./NewsPage";
export { default as AddNewsPage } from "./AddNewsPage";
